### ISSUE TITLE
AC08 Asset financial detail model

### ISSUE THREAD

**Issue by yarkalyba** [UheraAndrew/NewYork#10]
### Description

Entity 'AssetFinDet' should be created as one-2-one association with 'Asset'. The following properties should be present at the beginning:

- [x]  'acquireDate: Date' -- the date/time when asset was created or purchased.  

- [x]  'initCost: money' -- the initial cost of making or purchasing the asset. 

An instance of 'AssetFinDet' should be saved at the same time as a new instance of 'Asset'.

### Expected outcome

An entity modeling financial details for assets.

**Comment by SofiyaHevorhyan** [comment]
AssetDao.class has a weak implementation of save() method. Due to this some of the tests failed
Help wanted

**Comment by UheraAndrew** [comment]
save method was implemented in Issue-#18
