### ISSUE TITLE
AC08 Web UI for AssetFinDet

### ISSUE THREAD

**Issue by yarkalyba** [UheraAndrew/NewYork#11]
### Description

Entity `AssetFinDet` should be provided with a simple master and standalone center with the editions capabilities for properties `initCost` and `acquireDate`. Also, display a total amount of `initCost` for selected assets. 
### Expected outcome
The ability for users to enter and edit asset financial details.

**Comment by UheraAndrew** [comment]
Web ui was created in Issue-#18
