### ISSUE TITLE
AC09 Entity AssetTypeOwnership to manage the budget for the AssetType

### ISSUE THREAD

**Issue by SofiyaHevorhyan** [UheraAndrew/NewYork#18]
### Description

- [x] Create three entities `Role`, `Business Unit` and `Organisation` with a single-member composite property `name: String`. Property `desc: String` is also required.

- [x] Create an entity `AssetTypeOwnership` with a composite property `assetType: AssetType`. `AssetTypeOwnership` should also have those already mentioned three entities as **mutually-exclusive** properties where exactly one and only one of them can be assigned.

- [x] Also create a simple master and centre for `AssetTypeOwnership`

### Expected outcome

AssetType is associated to the applicable AssetOwner and the date/time of the association is recorded.

**Comment by yarkalyba** [comment]
The simple masters and centres for `Role`, `BusinessUnit`, and `Organisation` are also required.
