### ISSUE TITLE
AC-09 AssetOwnership functionality  

### ISSUE THREAD

**Issue by halonko** [UheraAndrew/NewYork#21]
### Description
Asset do not have Owner. It must be either Role, Business Unit, or Organization.

### Expected outcome
 

- [x] Logic for adding and editing AssetOwner with Asset master 
- [x] Update Web UI for AssetOwnership

**Comment by UheraAndrew** [comment]
Please test validators for the end date. in UI

**Comment by UheraAndrew** [comment]
We need to validate that the owner is the only one for each of Asset / AssetType.
