### ISSUE TITLE
Concurent asset ownership

### ISSUE THREAD

**Issue by UheraAndrew** [UheraAndrew/NewYork#25]
### Description
We could own Asset and AssetType by few users could use them in intersected periods.

### Expected outcome
You could not own Asset/AssetType in intersected period time

**Comment by halonko** [comment]
Забиваєм хуй

**Comment by halonko** [comment]
Hey!
I`m very sorry, did not know that



ср, 6 жовт. 2021 о 15:04 01es ***@***.***> пише:
