### ISSUE TITLE
AC04 Condition Ratings Model and UI

### ISSUE THREAD

**Issue by elenalazarus** [UheraAndrew/NewYork#5]
- [x] Create an activatable entity ConditionalRating with a single-member composite property name: String. Need properties desc: String, planDate (date of maintenance and/or replacement
activities).

- [x] Create property assetType: AssetType to allocate conditional ratings to asset types.

- [x]  Create UI for reviewing, editing and creating new asset type instances.

**Comment by UheraAndrew** [comment]
We need to add field urgency as a measurable field for condition
