### ISSUE TITLE
AC05 Asset Registration and Classification

### ISSUE THREAD

**Issue by halonko** [UheraAndrew/NewYork#6]
### Description

- [x] Create a table for asset creation that will have:
    - [x]  1  Name field
    - [x]  2 Description field
    - [x]  3 Active/Inactive checkbox
    - [x]  4 Associate with relevant `AssetType`

- [x] Create unique ID for all assets

### Expected outcome
The ability to register, classify and provide maintenance for Asset object

**Comment by SofiyaHevorhyan** [comment]
An automatic key assignment to asset registration is implemented but it's weak. The improvement is needed

**Comment by SofiyaHevorhyan** [comment]
Save method in AssetDao shoud be improved. That will also fix some problems in other issues
